/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as JourDayIdRouteImport } from './routes/jour/$dayId'
import { Route as AppSouvenirsRouteImport } from './routes/_app/souvenirs'
import { Route as AppInfosRouteImport } from './routes/_app/infos'
import { Route as JourDayIdSouvenirNouveauRouteImport } from './routes/jour/$dayId_.souvenir.nouveau'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const JourDayIdRoute = JourDayIdRouteImport.update({
  id: '/jour/$dayId',
  path: '/jour/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSouvenirsRoute = AppSouvenirsRouteImport.update({
  id: '/souvenirs',
  path: '/souvenirs',
  getParentRoute: () => AppRoute,
} as any)
const AppInfosRoute = AppInfosRouteImport.update({
  id: '/infos',
  path: '/infos',
  getParentRoute: () => AppRoute,
} as any)
const JourDayIdSouvenirNouveauRoute =
  JourDayIdSouvenirNouveauRouteImport.update({
    id: '/jour/$dayId_/souvenir/nouveau',
    path: '/jour/$dayId/souvenir/nouveau',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/infos': typeof AppInfosRoute
  '/souvenirs': typeof AppSouvenirsRoute
  '/jour/$dayId': typeof JourDayIdRoute
  '/jour/$dayId/souvenir/nouveau': typeof JourDayIdSouvenirNouveauRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/infos': typeof AppInfosRoute
  '/souvenirs': typeof AppSouvenirsRoute
  '/jour/$dayId': typeof JourDayIdRoute
  '/': typeof AppIndexRoute
  '/jour/$dayId/souvenir/nouveau': typeof JourDayIdSouvenirNouveauRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/infos': typeof AppInfosRoute
  '/_app/souvenirs': typeof AppSouvenirsRoute
  '/jour/$dayId': typeof JourDayIdRoute
  '/_app/': typeof AppIndexRoute
  '/jour/$dayId_/souvenir/nouveau': typeof JourDayIdSouvenirNouveauRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/infos'
    | '/souvenirs'
    | '/jour/$dayId'
    | '/jour/$dayId/souvenir/nouveau'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/infos'
    | '/souvenirs'
    | '/jour/$dayId'
    | '/'
    | '/jour/$dayId/souvenir/nouveau'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/infos'
    | '/_app/souvenirs'
    | '/jour/$dayId'
    | '/_app/'
    | '/jour/$dayId_/souvenir/nouveau'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  JourDayIdRoute: typeof JourDayIdRoute
  JourDayIdSouvenirNouveauRoute: typeof JourDayIdSouvenirNouveauRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/jour/$dayId': {
      id: '/jour/$dayId'
      path: '/jour/$dayId'
      fullPath: '/jour/$dayId'
      preLoaderRoute: typeof JourDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/souvenirs': {
      id: '/_app/souvenirs'
      path: '/souvenirs'
      fullPath: '/souvenirs'
      preLoaderRoute: typeof AppSouvenirsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infos': {
      id: '/_app/infos'
      path: '/infos'
      fullPath: '/infos'
      preLoaderRoute: typeof AppInfosRouteImport
      parentRoute: typeof AppRoute
    }
    '/jour/$dayId_/souvenir/nouveau': {
      id: '/jour/$dayId_/souvenir/nouveau'
      path: '/jour/$dayId/souvenir/nouveau'
      fullPath: '/jour/$dayId/souvenir/nouveau'
      preLoaderRoute: typeof JourDayIdSouvenirNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppInfosRoute: typeof AppInfosRoute
  AppSouvenirsRoute: typeof AppSouvenirsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInfosRoute: AppInfosRoute,
  AppSouvenirsRoute: AppSouvenirsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  JourDayIdRoute: JourDayIdRoute,
  JourDayIdSouvenirNouveauRoute: JourDayIdSouvenirNouveauRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
