/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSouvenirsRouteImport } from './routes/_app/souvenirs'
import { Route as AppInfosRouteImport } from './routes/_app/infos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSouvenirsRoute = AppSouvenirsRouteImport.update({
  id: '/souvenirs',
  path: '/souvenirs',
  getParentRoute: () => AppRoute,
} as any)
const AppInfosRoute = AppInfosRouteImport.update({
  id: '/infos',
  path: '/infos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/infos': typeof AppInfosRoute
  '/souvenirs': typeof AppSouvenirsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/infos': typeof AppInfosRoute
  '/souvenirs': typeof AppSouvenirsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/infos': typeof AppInfosRoute
  '/_app/souvenirs': typeof AppSouvenirsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/infos' | '/souvenirs'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/infos' | '/souvenirs' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/infos'
    | '/_app/souvenirs'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/souvenirs': {
      id: '/_app/souvenirs'
      path: '/souvenirs'
      fullPath: '/souvenirs'
      preLoaderRoute: typeof AppSouvenirsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infos': {
      id: '/_app/infos'
      path: '/infos'
      fullPath: '/infos'
      preLoaderRoute: typeof AppInfosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInfosRoute: typeof AppInfosRoute
  AppSouvenirsRoute: typeof AppSouvenirsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInfosRoute: AppInfosRoute,
  AppSouvenirsRoute: AppSouvenirsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
